### ISSUE TITLE
PluginFinder.cs compile error

### ISSUE THREAD

**Issue by abrca** [WildGums/SolutionGenerator#205]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X] .NET Core

## Component

SolutionGenerator\Extensibility\PluginFinder.cs

## Version of Library
latest from github

## Version of OS(s) listed above with issue
Windows 10 x64

## Steps to Reproduce
1. Compile

## Expected Behavior
no errors

## Actual Behavior

Error in  `protected override bool IsPlugin(Type type)` in SolutionGenerator\Extensibility\PluginFinder.cs 

Probably latest changes in Orc.Extensibility broke API:

PluginFinderBase.cs:
```
namespace Orc.Extensibility
{
    public abstract class PluginFinderBase : IPluginFinder
    {
[...]
        protected abstract bool IsPlugin(PluginProbingContext context, Type type);

```

**Comment by GeertvanHorrik** [comment]
This is indeed a breaking change that we had to do in Orc.Extensibility for .net core support. We haven't had time to update SG yet. Interested in doing a PR?

**Comment by abrca** [comment]
Fixing _this_ issue is simple, but in my case a lot of runtime exceptions appeared.
I'll try in another environment and write later
