### ISSUE TITLE
Error on generation

### ISSUE THREAD

**Issue by birama** [WildGums/SolutionGenerator#51]
Entry assembly could not be determined, returning Orchestra.Core as fallback
Entry assembly could not be determined, returning Orchestra.Core as fallback
Entry assembly could not be determined, returning Orchestra.Core as fallback
Entry assembly could not be determined, returning Orchestra.Core as fallback
Starting Solution Generator v1.0.0.0 (1.0.0.0, manually built in Visual Studio)
Checking if software was correctly closed previously
Confirming that application was started successfully
Failed to load assembly 'E:\DEV\SolutionGenerator\output\release\SolutionGenerator\lib\win32\x64\git2-15e1193.dll' for reflection, ignoring as possible plugin container | [BadImageFormatException] System.BadImageFormatException: Impossible de charger le fichier ou l'assembly 'file:///E:\DEV\SolutionGenerator\output\release\SolutionGenerator\lib\win32\x64\git2-15e1193.dll' ou une de ses dépendances. Le module était censé contenir un manifeste de l'assembly.
Failed to load assembly 'E:\DEV\SolutionGenerator\output\release\SolutionGenerator\lib\win32\x86\git2-15e1193.dll' for reflection, ignoring as possible plugin container | [BadImageFormatException] System.BadImageFormatException: Impossible de charger le fichier ou l'assembly 'file:///E:\DEV\SolutionGenerator\output\release\SolutionGenerator\lib\win32\x86\git2-15e1193.dll' ou une de ses dépendances. Le module était censé contenir un manifeste de l'assembly.
Failed to load assembly 'E:\DEV\SolutionGenerator\output\release\SolutionGenerator\lib\win32\x64\git2-15e1193.dll' for reflection, ignoring as possible plugin container | [BadImageFormatException] System.BadImageFormatException: Impossible de charger le fichier ou l'assembly 'file:///E:\DEV\SolutionGenerator\output\release\SolutionGenerator\lib\win32\x64\git2-15e1193.dll' ou une de ses dépendances. Le module était censé contenir un manifeste de l'assembly.
Failed to load assembly 'E:\DEV\SolutionGenerator\output\release\SolutionGenerator\lib\win32\x86\git2-15e1193.dll' for reflection, ignoring as possible plugin container | [BadImageFormatException] System.BadImageFormatException: Impossible de charger le fichier ou l'assembly 'file:///E:\DEV\SolutionGenerator\output\release\SolutionGenerator\lib\win32\x86\git2-15e1193.dll' ou une de ses dépendances. Le module était censé contenir un manifeste de l'assembly.
Found '2' plugins
  * SolutionGenerator.Templates.CatelWpfApp 1.0.0.0, manually built in Visual Studio, created by WildGums (E:\DEV\SolutionGenerator\output\release\SolutionGenerator\templates\SolutionGenerator.Templates.CatelWpfApp\SolutionGenerator.Templates.CatelWpfApp.dll)
  * SolutionGenerator.Templates.OrcComponent 1.0.0.0, manually built in Visual Studio, created by WildGums (E:\DEV\SolutionGenerator\output\release\SolutionGenerator\templates\SolutionGenerator.Templates.OrcComponent\SolutionGenerator.Templates.OrcComponent.dll)
Instantiating plugin 'SolutionGenerator.Templates.CatelWpfApp.CatelWpfAppTemplateDefinition'
Validating template data
Generating the solution
Failed to generate the solution | [ArgumentNullException] System.ArgumentNullException: La valeur ne peut pas être null.

**Comment by GeertvanHorrik** [comment]
Thanks for reporting, we haven't really been updating the WPF app template and it's outdated. Best to copy/paste from other apps (like LogViewer (see https://github.com/wildgums/logviewer)).
